### ISSUE TITLE
MyBB group promotion system - add parameter - thanks/like given

### ISSUE THREAD

**Issue by Cu8eeeR** [Cu8eeeR/MyBB_Thank-you-like-plugin#101]
Here, I would like to write all ideas how to improve new added feature group promotion in v1.9.10:
- Add a new parameter Thanks/like GIVEN for promotion - now we have only thanks/like received

@SvePu - thank you again for your time and work, excellent! Really good addition.

**Comment by Cu8eeeR** [comment]
@SvePu - is possible to add this? Now we have "Thanks/likes received", I would like to add "Thanks/like given" to make this feature complete.

If it is not possible, feel free to close this issue.

**Comment by SvePu** [comment]
@Cu8eeeR  I'm working on it ;)

**Comment by Cu8eeeR** [comment]
@SvePu - ok, add features one by one - this one should be added and finished. then we can move to others.
