### ISSUE TITLE
php error - tylsearch

### ISSUE THREAD

**Issue by Cu8eeeR** [Cu8eeeR/MyBB_Thank-you-like-plugin#111]
/tylsearch.php?action=results&uid=1&sid[]= got ot that

https://u.pomf.is/mnfzmq.mp4

**Comment by SvePu** [comment]
I can't reproduce this issue on my local mybb installation. I get a normal error message.

![php error - tylsearch 111](https://cloud.githubusercontent.com/assets/9826631/17462661/a7323a7a-5cb4-11e6-8d2c-dc08f49e5af3.PNG)

**Comment by Cu8eR** [comment]
Strange... maybe is it related to a specific version of php? I cannot reproduce either

**Comment by Cu8eeeR** [comment]
@SvePu - can we close this issue?

**Comment by SvePu** [comment]
maybe it's a main problem and not a plugin issue

**Comment by Cu8eeeR** [comment]
I am closing than _)
