### ISSUE TITLE
Post Like Search Bug

### ISSUE THREAD

**Issue by ST-Duman** [Cu8eeeR/MyBB_Thank-you-like-plugin#112]
Theres a bug with post like search. User has given 3 likes, when I search it I see 11 results. 

Every post has shown as how much likes its have.

User liked 3 posts
I search for posts he liked.

1st post he liked has 3 likes so I see it 3 times in search result.
2nd post he liked has 5 likes so I see it 5 times.
3rd post he liked has 3 likes so I see it 3 times.

That causes 11 results for 3 total likes.

If others are not experiencing this bug, I would appreciate having original php file with no bug.

**Comment by Cu8eeeR** [comment]
@SvePu - can you please confirm this?

**Comment by Cu8eeeR** [comment]
@SvePu - can you confirm this issue? I dont know how to reproduce it properly. :(

**Comment by SvePu** [comment]
@Cu8eeeR - I also can't reproduce this issue.

We'll keep it under observation.

**Comment by Cu8eeeR** [comment]
@MyBB-Andro - can you try to reproduce this issue please?

**Comment by SvePu** [comment]
@Cu8eeeR - Yes I can confirm this issue.

![unbenannt](https://cloud.githubusercontent.com/assets/9826631/22347710/406980aa-e409-11e6-94c3-f69fc85448cf.PNG)

![unbenannt1](https://cloud.githubusercontent.com/assets/9826631/22347716/489656e0-e409-11e6-84ce-f6cc7f6907e1.PNG)

**Comment by Cu8eeeR** [comment]
@SvePu - great, I tried but I misunderstood the report a little bit :(

**Comment by MyBB-Andro** [comment]
@Cu8eeeR Yes, i can also confirm this.

**Comment by SvePu** [comment]
added a fix for the search bug .... could anyone test it?

**Comment by Cu8eeeR** [comment]
I will try to test it ASAP (propably after work, it will be around 18:00). Thank you!

**Comment by Cu8eeeR** [comment]
@SvePu - Hi, I tested - it works fine!
