### ISSUE TITLE
CSS is deleted after upgrading to MyBB v1.8.9

### ISSUE THREAD

**Issue by Cu8eeeR** [Cu8eeeR/MyBB_Thank-you-like-plugin#117]
May reports here:
https://community.mybb.com/thread-169382-post-1258186.html#pid1258186

@SvePu - what do you think? I cannot find any issue

**Comment by SvePu** [comment]
If it is during major forum update we can't do anything. User have to save his own CSS changes and paste them after update / plugin reinstallation.
