### ISSUE TITLE
1.10.0 release

### ISSUE THREAD

**Issue by Cu8eeeR** [Cu8eeeR/MyBB_Thank-you-like-plugin#118]
I think we can release a new version soon. Thank you very much @SvePu for your contribution!

It would be really nice to solve these issues before we release anything out. Reject/confirm/implement them.

#112 - search bug - tylsearch.php
#121 - own TYL search list - tylsearch.php

@SvePu - can you please look for these four? Thank you

**Comment by Cu8eeeR** [comment]
#109 solved, 3 left

**Comment by Cu8eeeR** [comment]
#117 solved, 2 left

**Comment by SvePu** [comment]
#114 solved, 2 left

**Comment by Cu8eeeR** [comment]
Great! Thank you!

**Comment by Cu8eeeR** [comment]
Maybe we can mark a new version as 1.10.0 :)

**Comment by MyBB-Andro** [comment]
Good idea @Cu8eeeR , since many changes happened in this version.

**Comment by Cu8eeeR** [comment]
@SvePu - thank you for your pre-installation feature. Last thing is missing #25 - show remaining thx/like in top right corner popup - am I right? Is it something what can be added easily or we will release v1.10.0 without this and make a bug fix version including the missing popup feature? There might be more bugs/errors after release when we get more "testers"

**Comment by Cu8eeeR** [comment]
Done! Thx @SvePu !
