### ISSUE TITLE
Remove own Thanks/Likes from TYL search list

### ISSUE THREAD

**Issue by SvePu** [Cu8eeeR/MyBB_Thank-you-like-plugin#121]
#114

**Comment by Cu8eeeR** [comment]
@SvePu - good job, can you please check this report too? 

#112

**Comment by Cu8eeeR** [comment]
Hi @SvePu - any progress with this issue?

**Comment by SvePu** [comment]
@Cu8eeeR - Not yet, I'm always looking for a solution.
