### ISSUE TITLE
Remove recount tool is not a good idea :(

### ISSUE THREAD

**Issue by Cu8eeeR** [Cu8eeeR/MyBB_Thank-you-like-plugin#125]
@SvePu - I dont think that removing that is useful. ME and others use this feature when the error occurs (thanks/like are not counter properly etc.).

Is there any specific reason why to remove it?

I made a new branch which contains recount tool. 
https://github.com/Cu8eeeR/MyBB_Thank-you-like-plugin/tree/master-recount
So we can easily revert back in any case.

**Comment by SvePu** [comment]
We don't need it anymore - tyl recount functions are now in main plugin file

**Comment by Cu8eeeR** [comment]
@SvePu - I am sorry, you are right! I missed this change :(
