### ISSUE TITLE
Rename templates

### ISSUE THREAD

**Issue by Cu8eeeR** [Cu8eeeR/MyBB_Thank-you-like-plugin#126]
We should follow MyBB template naming:
- rename these templates: 
* thankyoulike -> thankyoulike_postbit
* thankyoulike_classic -> thankyoulike_postbit_classic
* thankyoulike_postbit ->thankyoulike_postbit_author_user
* thankyoulike_memprofile -> thankyoulike_member_profile

What do you think @SvePu ?

**Comment by MyBB-Andro** [comment]
That would be good and easy to find linked templates as same template name with thankyoulike_ prefix. Good idea indeed.

**Comment by Cu8eeeR** [comment]
v1.9.12 is really close, we just need someone who knows more about JS :( because of this last issue
#25 

Templates will be renamed in 1.9.12.

**Comment by SvePu** [comment]
Done.... ;)

**Comment by Cu8eeeR** [comment]
Thank you!
