### ISSUE TITLE
Links executing JS functions should return false and point to javascript.void(0) instead of hashtags

### ISSUE THREAD

**Issue by Cu8eeeR** [Cu8eeeR/MyBB_Thank-you-like-plugin#130]
We should apply same approach as MyBB in v1.8.9 - Links executing JS functions should return false and point to javascript.void(0) instead of hashtags.

https://github.com/mybb/mybb/issues/2522

**Comment by SvePu** [comment]
Quick fix ;)

**Comment by Cu8eeeR** [comment]
Thank you!
