### ISSUE TITLE
Extra space in statistics (member profile)

### ISSUE THREAD

**Issue by Cu8eeeR** [Cu8eeeR/MyBB_Thank-you-like-plugin#131]
@SvePu - I am sorry but I lent a picture from you :)

There is a small bug - an extra space after "...percent of total )"

![bug](https://cloud.githubusercontent.com/assets/778890/22347988/4a135f44-e40a-11e6-8d10-34eccb555f29.PNG)

**Comment by SvePu** [comment]
@Cu8eeeR - No problem ;)

I guess this is defined in the lang file

**Comment by SvePu** [comment]
Thx @MyBB-Andro .... but it's not the right fix

**Comment by SvePu** [comment]
It was a wrong variables in lang file and some missing code parts :|

![unbenannt](https://cloud.githubusercontent.com/assets/9826631/22355100/01c121a8-e429-11e6-9047-1da22dc4e71b.PNG)

**Comment by Cu8eeeR** [comment]
Thank you @SvePu !
