### ISSUE TITLE
Lang for ACP is missing

### ISSUE THREAD

**Issue by Cu8eeeR** [Cu8eeeR/MyBB_Thank-you-like-plugin#133]
The issue is that the language path is wrong
`/inc/languages/english/config_thankyoulike.lang.php`

it should be
`/inc/languages/english/**admin/**config_thankyoulike.lang.php`

**Comment by SvePu** [comment]
@Cu8eeeR ??????
![unbenannt](https://cloud.githubusercontent.com/assets/9826631/22381747/1d07e312-e4c3-11e6-8d94-bbccbc33e079.PNG)

**Comment by Cu8eeeR** [comment]
Yes, it is correct but TYL plugin has a bad path to this file. It shows error that the lang file does not exist

**Comment by SvePu** [comment]
where?

**Comment by Cu8eeeR** [comment]
![lang](https://cloud.githubusercontent.com/assets/778890/22381884/b46f8cf0-e4c3-11e6-8f90-d134845e04e9.png)

The path is wrong

**Comment by SvePu** [comment]
Looks like a bug in mybb 1.8.10

**Comment by Cu8eeeR** [comment]
I havent checked, other plugins should be fine, but I havent tested yet.

**Comment by SvePu** [comment]
Please try: https://github.com/Cu8eeeR/MyBB_Thank-you-like-plugin/commit/84f3456fc0af16ffdc33b805f51f4923259d09c8

**Comment by Cu8eeeR** [comment]
@SvePu - I will try as soon as possible, thank you for your fast fix!

**Comment by Cu8eeeR** [comment]
Works correctly 👍
