### ISSUE TITLE
Check if old templates/css are not deleted

### ISSUE THREAD

**Issue by Cu8eeeR** [Cu8eeeR/MyBB_Thank-you-like-plugin#137]
@SvePu 

Is possible to delete old templates (templates before renaming) + old css on install? They can still remain here when user doesnt perform proper deactivate->activate on upgrade

**Comment by SvePu** [comment]
I'll include a cleanup function ;)

**Comment by Cu8eeeR** [comment]
@SvePu - thank you!

**Comment by SvePu** [comment]
Done! ;)
