### ISSUE TITLE
PHP error in post preview

### ISSUE THREAD

**Issue by SvePu** [Cu8eeeR/MyBB_Thank-you-like-plugin#142]
> After the update people started to get HTTP ERROR 500 when they tried to preview the post they are sending. 

https://community.mybb.com/thread-169382-post-1261902.html#pid1261902

**Comment by SvePu** [comment]
Sorry, my fault!

**Comment by SvePu** [comment]
I modified the 2.0.0 release und uploaded the new files to MyBB mod page

**Comment by Cu8eeeR** [comment]
Nevermind, it happens :) Thank you for your fix!
