### ISSUE TITLE
Tapatalk - user's statistics - missing language variable

### ISSUE THREAD

**Issue by Cu8eeeR** [Cu8eeeR/MyBB_Thank-you-like-plugin#143]
v2.0.0 - there is a missing lang for statistics in member profile (Tapatalk).
![687474703a2f2f692e696d6775722e636f6d2f396d7a6651555a2e6a7067](https://cloud.githubusercontent.com/assets/778890/22520884/4df3be32-e8b6-11e6-9e92-ea81f1613e57.jpg)

reported by @MyBB-Andro over PM

**My opinion:**
I dont use Tapatalk, it is propably their issue in heir app (or MyBB Tapatalk plugin). We changed some lang strings in last version, they should adapt these changes. I wont contact them anyway, because I hate Tapatalk after their latest changes (1 year back).

**Comment by SvePu** [comment]
I have no idea...maybe there is a similar php variable in Tapatalk script.

**Comment by MyBB-Andro** [comment]
Actually other than this no issues with tapatalk. So i would like to request you not to remove tapatalk support. Many comnunity use this plugin instead of new ones because of tapatalk support.

**Comment by SvePu** [comment]
I could change the php variables for a test

**Comment by MyBB-Andro** [comment]
Let me know the change, so i can apply the patch and confirm you back. Thank you.

**Comment by Cu8eeeR** [comment]
@MyBB-Andro contacted Tapatalk support, so we will see. It is their issue, they have to update they plugin

**Comment by SvePu** [comment]
@MyBB-Andro - Please unzip the attached file and copy the thankyoulike.php in plugins folder ... after that, test it please

[thankyoulike.zip](https://github.com/Cu8eeeR/MyBB_Thank-you-like-plugin/files/748571/thankyoulike.zip)

**Comment by MyBB-Andro** [comment]
Okay, i tested it @SvePu , unfortunately that didn't fixed the issue.

**Comment by SvePu** [comment]
@MyBB-Andro - I found a script issue, please test this fix => https://github.com/Cu8eeeR/MyBB_Thank-you-like-plugin/commit/7d39df568dcf5358312cf445baa6a22ac7fa04ad

**Comment by SvePu** [comment]
Fixed in #144

**Comment by Cu8eeeR** [comment]
Good job guys!
