### ISSUE TITLE
Add support for custom css class for post when get X amount of thx/likes (template conditionals plugin)

### ISSUE THREAD

**Issue by Cu8eeeR** [Cu8eeeR/MyBB_Thank-you-like-plugin#148]
This addition would be really nice and useful. If the post get "X" likes/thx -> highlight it (add a custom css class for customization). We could use template conditionals plugin).

https://community.mybb.com/thread-169382-post-1270723.html#pid1270723

@SvePu - what do you think, is there any other easier way to do it?

**Comment by SvePu** [comment]
Open the inc/plugins/thankyoulike.php and insert right above [this line](https://github.com/Cu8eeeR/MyBB_Thank-you-like-plugin/blob/master/inc/plugins/thankyoulike.php#L1097):
```php
$post['styleclass'] = '';

if($post['tyl_pnumtyls'] > xxx) //xxx = number of thanks/likes when the magic happens.
{
	$post['styleclass'] =  ' popular_post';
}
```
Then you have to edit the theme templates ```postbit``` and ```postbit_classic```:

Search for:
```html
<div class="post {$unapproved_shade}" style="{$post_visibility}" id="post_{$post['pid']}">
```
Replace with:
```html
<div class="post{$post['styleclass']} {$unapproved_shade}" style="{$post_visibility}" id="post_{$post['pid']}">
```
After that you can style your postbits with CSS class ```.popular_post```

That's it! ;)

**Comment by Cu8eeeR** [comment]
@SvePu - thats great, amazing, thank you!

Can we add it into the TYL system with On/Off setting?

**Comment by thelovelyone** [comment]
@SvePu Any idea how i can add a fa icon to the post if it hits x likes? I tried, but nothing worked.

Like this: http://image.prntscr.com/image/581e74db863d48639d7b7b227cef8090.jpeg

**Comment by Cu8eeeR** [comment]
@thelovelyone - did you try :after pseudo tag? https://css-tricks.com/almanac/selectors/a/after-and-before/

**Comment by thelovelyone** [comment]
Yea, 'before' worked, i got the icon on the top right, however its overlapping with the content and the moderation checkbox for example.

**Comment by SvePu** [comment]
@Cu8eeeR - please review the changes.

**Comment by Cu8eeeR** [comment]
@SvePu - hi, thank you! Looks fine, I will make just a small changes in language file

**Comment by Cu8eeeR** [comment]
@SvePu - just these improvements:
* add default .popular_class with styling into thankyoulike.css - my idea something like this:
`border: 2px solid; border-radius: 3px; border-color: rgba(112,202,47,0.5); background-color: rgba(139,195,74,0.3);`
* add missing "classic" here: https://github.com/Cu8eeeR/MyBB_Thank-you-like-plugin/commit/44db6044d8cb20d5ac93b852f82e299a423464a6#diff-61561fd3f118cc16cdc5c0bbb79b38c7R573
* I changed lang file a little bit, feel free to adjust it on your own

**Comment by SvePu** [comment]
@Cu8eeeR  - I added desired changes

**Comment by Cu8eeeR** [comment]
@SvePu - thx, looks fine!
