### ISSUE TITLE
How to remove "," when likes number hits 1000+ ?

### ISSUE THREAD

**Issue by thelovelyone** [Cu8eeeR/MyBB_Thank-you-like-plugin#150]
Basically what it says above, how do you remove the comma (postbit and profile)?

http://image.prntscr.com/image/9bd149f2d5ad46dab7bd9cba3bb3885a.jpeg

**Comment by SvePu** [comment]
You can define it with the **Thousands Numeric Separator** settings in ACP > Settings > General Configuration

**Comment by thelovelyone** [comment]
Oh, thanks, didn't know that.
