### ISSUE TITLE
Display fails to update on MyBB 1.8.12 - Json returns empty

### ISSUE THREAD

**Issue by djmojacar** [Cu8eeeR/MyBB_Thank-you-like-plugin#151]
After updating MyBB to 1.8.12 and plugin to 2.0.2 the ajax refresh is broken for the user.

After the user clicks Thank You, the ajax does its stuff but the Json returned is empty so all the user sees is two lines of **:** as in this screenshot
![captura de pantalla completa 01072017 84148](https://user-images.githubusercontent.com/29810563/27759772-3b5505c6-5e39-11e7-9e79-c49dcc4e83f3.jpg)

In the Json returned I get:
`**tylButton** = "<div id="tyl_btn_15122" class="postbit_buttons"><a class="del_tyl_button" href="thankyoulike.php?action=del&amp;pid=15122&amp;my_post_key=3304975cfa84448b98c01bafca28a123" onclick="return thankyoulike.del(15122, 1977);" title="Remove Thank You" id="tyl_a15122"><span id="tyl_i15122">Remove Thank You</span></a></div>"`
`**tylData** = "\n: \n<br />\n: \n"`

**Comment by Cu8eeeR** [comment]
Thx for your report, unfortunately it is related to your theme (you dont use the default MyBB theme, am I right?)

Check the thread on MyBB board - a lot of users reported same issue, there is a fix :)
