### ISSUE TITLE
Time and date issue on mouse hover

### ISSUE THREAD

**Issue by Cu8eeeR** [Cu8eeeR/MyBB_Thank-you-like-plugin#152]
@SvePu 

https://community.mybb.com/thread-169382-post-1278045.html#pid1278045

This bug is a regression from since MyBB v1.8.11 (https://github.com/mybb/mybb/pull/2753), should be fixed soon (v1.8.13 maybe?). Is there anything else what can we do for this?

**Comment by SvePu** [comment]
We could provide a quick fix for that by changing of ```mydate``` to ```date``` in [these two lines](https://github.com/Cu8eeeR/MyBB_Thank-you-like-plugin/blob/master/inc/plugins/thankyoulike.php#L962-L963) of main plugin file.

**Comment by Cu8eeeR** [comment]
@SvePu - ok, thats would be fine :)
