### ISSUE TITLE
Maximum like/thanks in a time period

### ISSUE THREAD

**Issue by Cu8eeeR** [Cu8eeeR/MyBB_Thank-you-like-plugin#25]
Add how many likes/thanks can a specific usergroup give per XX time.

For example for registered users 10 likes per 24 hours etc.
- amount of likes/thanks can be changed
- time period should be in hours

**Comment by Cu8eR** [comment]
We can use default MyBB rep system setting for every usergroup (same as Thank system from DarkNeo does)

**Comment by SvePu** [comment]
Not finished.....we'll need an Ajax (JS) fix

**Comment by Cu8eeeR** [comment]
@SvePu - thats really great! Excellent, keep good work!

**Comment by SvePu** [comment]
@Cu8eeeR - I guess we'll need an AJAX guru .... I try and try but it doesn't perform as it should.

**Comment by Cu8eeeR** [comment]
I dont know anybody with these required skills :(

Can we take any hint from https://github.com/WhiteNeo/thankyou-mybb-system ?

**Comment by Cu8eeeR** [comment]
@wildcard - hi buddy, can you give us any hint? Thank you!

**Comment by wildcard** [comment]
I'll try my best, what exactly are you trying to do?
Not familiar with MyBB though.

קובי קדוש,
נשלח מה-iPhone שלי

**Comment by Cu8eeeR** [comment]
We added a new feature which is working fine - limited thanks given by a user/24 hodin period. We just need to add a new popup notification in the top right corner with a notice:
1) Daily limit of thanks reached (when the user gave all thnaks to users)
2) Show how many thanks remain

We already show notification in the top right corner by JGowl which is supported by MyBB and our plugin. We just cannot find the good way how to implement an error message.

Maybe @SvePu will write more than me. Thank you in advance

**Comment by wildcard** [comment]
1. What about http://t4t5.github.io/sweetalert/
2. Show a little tooltip/popover when hover the thanks Button.

קובי קדוש,
נשלח מה-iPhone שלי

**Comment by WildcardSearch** [comment]
Hi @Cu8eeeR,

I'll be a little busy this evening, but I'd be glad to take a look tomorrow, if that's okay.

**Comment by SvePu** [comment]
Hi and thank you guys!

Before the AJAX main magic happens we have to check for setted errors() with jGrowl error message.
Momentary I play with the thankyoulike.js

https://github.com/Cu8eeeR/MyBB_Thank-you-like-plugin/blob/master/jscripts/thankyoulike.js

We have to include:
```javascript
var json = $.parseJSON(request.responseText);
if(json.hasOwnProperty("errors"))
{
	$.each(json.errors, function(i, message)
	{
		$.jGrowl(message, {theme:'jgrowl_error'});
	});
}
```

**Comment by Cu8eeeR** [comment]
@WildcardSearch - no worries, thank you in advance!

@SvePu - is possible to add a notification in JGrowl how many thanks/likes remain (24 h). It will be shown after a user add/remove thanks/likes from post.

**Comment by SvePu** [comment]
@Cu8eeeR - Possible is almost everything ... but this will also need some JS (AJAX) magic.
I already prepared the needed PHP stuff.

![tyl_plugin_1](https://cloud.githubusercontent.com/assets/9826631/22031905/8d11ccce-dce2-11e6-907c-76913006faa8.png)

**Comment by Cu8eeeR** [comment]
Great, so now we need a guru for JS :(

**Comment by SvePu** [comment]
Yes...

**Comment by WhiteNeo** [comment]
Only add it as años xhlhttp_error vars.

Then add it tour json par se errors and done !!!

Copy my conde of thx con muy site

**Comment by SvePu** [comment]
@WhiteNeo - Thank you! Could you edit the thankyoulike.js and show me how it goes, please?

**Comment by Cu8eeeR** [comment]
@WhiteNeo - Hi, can you please tell us more about this? IT seems that you know much more about this issue than us, thank you very much!

**Comment by WhiteNeo** [comment]
Sorry for lately response.

I try to see it when i hace some free time.

Right now i am developing some projects.

My life and family are my priority right now.

See the file i mentioned there is the solution and is not a bug. Remove
jGrowl until i can see it.

**Comment by SvePu** [comment]
Main functions & error notifications are working now...

- "Show how many thanks remain" not included

**Comment by Cu8eeeR** [comment]
@SvePu - great! Really great, thank you very much!

**Comment by SvePu** [comment]
Includes displaying of time until next possibility to thankyou/like.

![tyl_plugin_timeleft](https://cloud.githubusercontent.com/assets/9826631/22182548/0b23a2ae-e0a8-11e6-95db-3ac96ab21065.png)

**Comment by Cu8eeeR** [comment]
Great! So last thing - show remaining thanks/like, right?

Can we add any styling for this popups? For examle make "Reached maximum thanks per 24 hours!" bold? (<strong></strong>)

**Comment by MyBB-Andro** [comment]
Light green BG for adding likes looks unprofessional to me, it should be Black background and white text to make it look decent with default mybb 1.8 theme. Please think about it guys.

**Comment by Cu8eeeR** [comment]
@MyBB-Andro - it uses MyBB default style (was added in 1.8.8-1.8.9)

**Comment by MyBB-Andro** [comment]
Wasn't aware sorry, if i am not wrong it was black bg before, with recent updates they made this change. No idea why!

**Comment by Cu8eeeR** [comment]
It is OK, maybe we can discuss this, it is only a CSS thing

**Comment by SvePu** [comment]
@MyBB-Andro - you can edit it in thankyoulike.css 

add:
```css
.jGrowl .jGrowl-notification.jgrowl_success,
.jGrowl .jGrowl-notification.jgrowl_error{
    background: black !important;
    border: 1px solid black !important;
    color: #fff !important;
}
```

@Cu8eeeR - modified the lang variable

**Comment by Cu8eeeR** [comment]
@SvePu - Great! You rock!

**Comment by SvePu** [comment]
Includes alert box to display "reached limit" info if jGrowl displaying is disabled

**Comment by Cu8eeeR** [comment]
@SvePu - nice, but can we use default MyBB error page for this? I mean a page with warning in a box and redirection link back.

**Comment by SvePu** [comment]
@Cu8eeeR - That own error page will called when Javascript is disabled on browser.

**Comment by Cu8eeeR** [comment]
@SvePu - I am sorry, you are right! ;)

Maybe can we add any styling for the alertbox or not? Ihave no experience with that. :/

**Comment by SvePu** [comment]
This is only emergency stuff ... users could enable jGrowl if they want it stylish. ;)

**Comment by Cu8eeeR** [comment]
@SvePu - yeah, thats true. I agree! Good work!

**Comment by Cu8eeeR** [comment]
@SvePu - do you have any ETA for the last missing part to make this complete? Thank you!

**Comment by SvePu** [comment]
Displaying of thanks / likes left is not necessary for the function, it's only a googie

We can mark this issue as solved ;)

**Comment by Cu8eeeR** [comment]
@SvePu - we can release a new version and add this feature later. I will release a new build ASAP today

**Comment by MyBB-Andro** [comment]
Before that please do one change @Cu8eeeR

Change hover text of "Like" button. It currently says "Like Post". Change it to "Like this Post". To match up with other mybb postbit buttons standards.

This is quite easy to do, so i don't think will consume much time. I am currently on mobile so unable to do.

Thanks

**Comment by Cu8eeeR** [comment]
Is it needed?

**Comment by SvePu** [comment]
Hey,

@MyBB-Andro - If you like you can harcode the desired title in plugin templates "thankyoulike_button_add" and "thankyoulike_button_add"

eg:
```html
<div id="tyl_btn_{$post['pid']}" class="postbit_buttons"><a class="add_tyl_button" href="thankyoulike.php?action=add&amp;pid={$post['pid']}&amp;my_post_key={$mybb->post_code}" onclick="thankyoulike.add({$post['pid']}, {$post['tid']}); return false;" title="Like this Post" id="tyl_a{$post['pid']}"><span id="tyl_i{$post['pid']}">{$lang->add_tyl}</span></a></div>
```
or

```html
<div id="tyl_btn_{$post['pid']}" class="postbit_buttons"><a class="del_tyl_button" href="thankyoulike.php?action=del&amp;pid={$post['pid']}&amp;my_post_key={$mybb->post_code}" onclick="thankyoulike.del({$post['pid']}, {$post['tid']}); return false;" title="Unlike this Post" id="tyl_a{$post['pid']}"><span id="tyl_i{$post['pid']}">{$lang->del_tyl}</span></a></div>
```

**Comment by Cu8eeeR** [comment]
New issue created
#140
