### ISSUE TITLE
More language support

### ISSUE THREAD

**Issue by Cu8eeeR** [Cu8eeeR/MyBB_Thank-you-like-plugin#58]
What about to add more language support?

@SvePu - German
@WhiteNeo - Spanish? I am not sure what is your native laguage
@Cu8eR - Czech

**Comment by WhiteNeo** [comment]
I finished the first lang spanish beta, but i need to test it, all files are up to date, new lang vars aare at the end of file.

Some few new vars have to add on new lang files, if you can to make files an new dirs for espanol lang dir and files blank or with same english content to update asap.

**Comment by Cu8eR** [comment]
Nice, I am working on Czech translation. I will add it after we finish another things

**Comment by WhiteNeo** [comment]
Nvm i upload my files to my own repo because i have to delete it because this mod i will never use it on my forum or others i really prefer to use my own mod, because is more easy for me to do new things, anyway i say i did not support this mod, so i have no intentions to do nothing else on this mod, i have to take many other plugins mine and have really no time to this mod anymore.

**Comment by Cu8eR** [comment]
@WhiteNeo - Well, OK anyway thank you very much for contributing! I hope you will find some free time to fix bugs or add another features in future.

**Comment by WhiteNeo** [comment]
Yes i take that on mind i delete my forked version to stay only whit this, i uploaded some translated beta files, becaause have to review it, but anyway it's better to make a version on all laangs if posible.

If i haaave free time i try to help with this, but my forum, life, and maany more it's my priority now i haave to take some time to set my forum on the best working way, then i take some rest for me and my family, friends and all my entire life then i back to help users of MyBB again :D

**Comment by Cu8eR** [comment]
Czech and German language are ready for next build - I just need to find someone to check German lang file which I prepared

**Comment by Cu8eR** [comment]
@SvePu - can I send you German translation? It should be checked before adding here. I found a german lang file for older version and added new lang var. Unfortunately, I cannot speak German :(

**Comment by SvePu** [comment]
German frontend lang file is ready...but I've to test it.

**Comment by Cu8eR** [comment]
@SvePu - frontend is enough, I have prepared Czech translation, it is ready to be release in 1.9.9

**Comment by Cu8eR** [comment]
Czech language for frontend has been added.

**Comment by SvePu** [comment]
We should add the different languages separately.
The basic package only should containing english lang files.

**Comment by Cu8eR** [comment]
I agree, how to maintain them? Just create a separate branch for languages?

**Comment by SvePu** [comment]
Any translator could make his own Github repo for this.
